## Frozen Lake Game Intsructions:
https://www.gymlibrary.dev/environments/toy_text/frozen_lake/

## Imports:

In [4]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

## Initialize Environment and Hyper Parameters:

In [5]:
env = gym.make("FrozenLake-v0")

In [6]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
num_episodes = 10000 # Total number of episodes our agent will play during training
max_steps_per_episode = 100 # Exceeding this in a single episode will terminate the episode with no reward

learning_rate = 0.1
discount_rate = 0.99

# We will use epsilon greedy strategy to solve exploration-exploitation problem
exploration_rate = 1 # Initial exploration rate
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

## Q-Learning Algorithm Using Value Iteration:

In [8]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset() # Reset the env back to the starting state
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Exploration-Exploitation trade-off:
        exploration_rate_threshold = random.uniform(0,1)
        if(exploration_rate_threshold > exploration_rate): # Exploitation (choose the action in the Q-table that has the hoghest q-value in the current state)
            action = np.argmax(q_table[state,:])
        else: # Exploartion (choose a random action)
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        # Update Q-tbale for Q(s,a), the new q_table[state,action] is the weighted sum of our old value and our new value
        q_table[state, action] = (1 - learning_rate)  * q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward

        if(done == True):
            break

    # Exploration rate decay:
    # Exploration rate decays/decreases at a rate proportional to its current value
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

## Calculate and print the average reward per thousand episodes:

In [9]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
for r in rewards_per_thousand_episodes:
  print(""+ str(count) + ": "+str(sum(r/1000)))
  count += 1000

1000: 0.048000000000000036
2000: 0.19700000000000015
3000: 0.3800000000000003
4000: 0.5400000000000004
5000: 0.6670000000000005
6000: 0.6660000000000005
7000: 0.6830000000000005
8000: 0.6610000000000005
9000: 0.7030000000000005
10000: 0.6680000000000005


## Print updated Q-table:

In [10]:
print(q_table)

[[0.53868993 0.49113229 0.49065806 0.49032607]
 [0.20473038 0.31404117 0.28621654 0.48039883]
 [0.40465842 0.39150273 0.40253836 0.45064642]
 [0.25893432 0.32711681 0.26545205 0.44122871]
 [0.55639581 0.40296089 0.45393588 0.29868778]
 [0.         0.         0.         0.        ]
 [0.16756418 0.09041766 0.39669108 0.14664505]
 [0.         0.         0.         0.        ]
 [0.26911493 0.34499917 0.39618497 0.6098838 ]
 [0.46305508 0.68380371 0.46065191 0.3390587 ]
 [0.68328439 0.40696717 0.37190575 0.32035505]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.55192043 0.5343802  0.78404234 0.48441764]
 [0.70156479 0.92167785 0.73372002 0.7065445 ]
 [0.         0.         0.         0.        ]]


## Watch The Agent Play After Training:

In [13]:
for episode in range(3):

  state = env.reset()
  done = False

  print("EPISODE "+str(episode)+"")

  time.sleep(1) # Sleep for 1 sec to have time to read that print

  for step in range(max_steps_per_episode):

    clear_output(wait = True) # Clears the output from the current cell of the notebook. wait = True means to wait to clear the output until another print overwrites it
    env.render()
    time.sleep(0.3)

    action = np.argmax(q_table[state,:]) # Select the action which has the highest q-value in our q-table in the current state
    new_state, reward, done, info = env.step(action)

    if(done):
      clear_output(wait=True)
      env.render()
      if(reward == 1):
        print("GOAL REACHED!!")
        time.sleep(3)

      else:
        print("YOU FELL :(")
        time.sleep(3)

      clear_output(wait=True)
      break

    state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
GOAL REACHED!!
